In [1]:
import numpy as np

In [2]:
print(np.__version__)

arr_1d = np.array([1, 2, 3])

arr_2d = np.array([[1, 2],
                    [3, 4]])


print(arr_1d)
print(arr_2d)

print(type(arr_1d))
print(type(arr_2d))

print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)



2.4.2
[1 2 3]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
2
(2, 2)
4


In [ ]:
# numpy function
def add_two_arrays(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return a + b

p = np.array([1, 2, 3])
q = np.array([4, 5, 6])

print(add_two_arrays(p, q))

[5 7 9]


In [ ]:
arr_2d_ndim = np.array([[1, 2],
                    [3, 4]],
                    ndmin = 3)

print(arr_2d_ndim.ndim)   # num of dimensions
print(arr_2d_ndim.shape)  # it's dimensions
print(arr_2d.size)        # num of elements

3
(1, 2, 2)
4


In [ ]:
arr = np.array([[1, 2, 3],
       [4, 5, 6], 
       [7, 8, 9]])

print(arr[0, 2])  # same as arr[0][2] which also works 
print(arr[0, -2])

3
2


In [ ]:
arr = np.array([[12, 13, 14], 
                [15, 16, 17]])

# how do i get 13 and 16 using [::] splice notation

print(arr[:,1]) # get the 1st column
print(arr[1, :]) # get the 1st row

print(arr[1, :][1::]) # get the 1st row, then get all starting from idx = 1

[13 16]
[15 16 17]
[16 17]


In [19]:
arr = np.array([1, 2, 3], dtype = 'S')

print(arr)

# typecast in numpy
s_arr = arr.astype(float)
print(s_arr)

[b'1' b'2' b'3']
[1. 2. 3.]


In [23]:
arr = np.array([1, 2, 3, 4, 5])

arr_copy = arr.copy() # only copies arr, in new location
arr_copy_memory = arr.view() # points to the same locations

print("arr:", arr)
print("arr_copy:", arr_copy)
print("arr_copy_memory:", arr_copy_memory)

arr_copy_memory[0] = 100

print("---------------")
print("arr:", arr)
print("arr_copy:", arr_copy)
print("arr_copy_memory:", arr_copy_memory)

arr: [1 2 3 4 5]
arr_copy: [1 2 3 4 5]
arr_copy_memory: [1 2 3 4 5]
---------------
arr: [100   2   3   4   5]
arr_copy: [1 2 3 4 5]
arr_copy_memory: [100   2   3   4   5]


In [25]:
arr = np.array([10, 20, 38, -27, 93])

print(f"sum = {np.sum(arr)}")
print(f"max = {np.max(arr)}")
print(f"min = {np.min(arr)}")

sum = 134
max = 93
min = -27


In [ ]:
arr_2d = np.array([[1, 2],
                    [3, 4]],
                    )
print("arr_2d = \n", arr_2d, "\n")

# we can reshape n x m to any shape r x c x ... as long as r x c x ... == n x m
# reshape doable iff. arr.size remains same (obviously)
arr_reshaped = arr_2d.reshape(4, 1)
print("reshaped array = ")
print(arr_reshaped, "\n")


# flatten to 1d array
print("flattened array = ")
arr_flat = arr_2d.flatten()
print(arr_flat)

arr_2d = 
 [[1 2]
 [3 4]] 

reshaped array = 
[[1]
 [2]
 [3]
 [4]] 

flattened array = 
[1 2 3 4]


In [ ]:
print(type(arr_flat))

# arithmatic with numpy arrays
print("arr = ", arr)
print("arr * 2 = ", arr * 2)
print("arr + 2 = ", arr + 2)
print("arr - 2 = ", arr - 2)
print("arr / 2 = ", arr / 2)
print("arr % 2 = ", arr % 2)

<class 'numpy.ndarray'>
arr =  [ 10  20  38 -27  93]
arr * 2 =  [ 20  40  76 -54 186]
arr + 2 =  [ 12  22  40 -25  95]
arr - 2 =  [  8  18  36 -29  91]
arr / 2 =  [  5.   10.   19.  -13.5  46.5]
[ 10  20  38 -27  93]
arr % 2 =  [0 0 0 1 1]


In [62]:
# np.arange(start, end, step)
a = np.arange(0, 10, 2)
print("arange:", a)

# np.linspace(start, end, how_many_u_want)
b = np.linspace(0, 10, 5)
print("linspace:", b)

# np.ones()
c = np.ones(5)
print("ones:", c)

c2 = np.ones((2, 3), dtype = np.int32)   
print("ones 2D:\n", c2)

# np.empty()
d = np.empty(5)
print("empty:", d)
# only use when you're about to overwrite every value yourself
# faster than zeros

e2 = np.zeros((2, 3))  

# np.sign()
f = np.array([-5, 0, 3, -2, 7])
print("sign:", np.sign(f))

print(type(d[0]))

print("\n these are typically float64, so use the dtype = np.intxx")

arange: [0 2 4 6 8]
linspace: [ 0.   2.5  5.   7.5 10. ]
ones: [1. 1. 1. 1. 1.]
ones 2D:
 [[1 1 1]
 [1 1 1]]
empty: [1. 1. 1. 1. 1.]
sign: [-1  0  1 -1  1]
<class 'numpy.float64'>

 these are typically float64, so use the dtype = np.intxx


In [ ]:
# array concatenations
a = np.arange(1, 12, 2)
b = np.arange(1, 24, 4)

print(f"a = {a}")
print(f"b = {b}")

print(f"np.concatenate((a, b)) USE 2 BRACKETS = {np.concatenate((a, b))}")

a = [ 1  3  5  7  9 11]
b = [ 1  5  9 13 17 21]
np.concatenate((a, b)) USE 2 BRACKETS = [ 1  3  5  7  9 11  1  5  9 13 17 21]


In [56]:
# hstack -> COLUMN NUM MUST BE SAME
print(f"np.vstack((a, b)) = {np.vstack((a, b))}")

# vstack -> ROW NUM MUST BE SAME
print(f"np.hstack((a, b)) = {np.hstack((a, b))}")


print("\nfor hstacking column num MUST BE SAME")
print("for vstacking row num MUST BE SAME")

np.vstack((a, b)) = [[ 1  3  5  7  9 11]
 [ 1  5  9 13 17 21]]
np.hstack((a, b)) = [ 1  3  5  7  9 11  1  5  9 13 17 21]

for hstacking column num MUST BE SAME
for vstacking row num MUST BE SAME


In [54]:
arr_condition = (a >= 9)
new_arr = a[arr_condition]

print(arr)
print(new_arr)

[False False False False  True  True]
[ 9 11]


In [65]:
# transposing in numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"arr               = \n {arr}")
print(f"arr.T             = \n {arr.T}")                          # method 1: .T attribute
print(f"np.transpose(arr) = \n {np.transpose(arr)}")  # method 2: np.transpose()
print(f"arr.transpose()   = \n {arr.transpose()}")    # method 3: .transpose() method

arr               = 
 [[1 2 3]
 [4 5 6]]
arr.T             = 
 [[1 4]
 [2 5]
 [3 6]]
np.transpose(arr) = 
 [[1 4]
 [2 5]
 [3 6]]
arr.transpose()   = 
 [[1 4]
 [2 5]
 [3 6]]


In [66]:
# np.array_split()

arr = np.arange(10)   # [0 1 2 3 4 5 6 7 8 9]

print(np.array_split(arr, 3))
# [array([0,1,2,3]), array([4,5,6]), array([7,8,9])]
# splits into 3 parts -- unevenly if it doesn't divide evenly (np.split() would error here)

print(np.array_split(arr, 5))
# [array([0,1]), array([2,3]), array([4,5]), array([6,7]), array([8,9])]
# evenly divides since 10/5 = 2

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

# prints all the elements in row-major 
for idx, x in np.ndenumerate(arr):
    print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
