In [9]:
class Employee:
    class_name = 'Employee'

    # double underscore -> dunder
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __str__(self):
        return f"{self.id} with name {self.name}"
    
    def __repr__(self):
        return f"{self.name} has the id {self.id}"

employee = Employee(2596, "Kirk")
print(employee)
employee

2596 with name Kirk


Kirk has the id 2596

In [10]:
employee.class_name

'Employee'

In [ ]:
import numpy as np

a = np.array((1,2,3,4), dtype=np.int16)
b = [1,2,3,4]

a[0] = 111
print(a, "this is how a numpy array is printed")
print(b, "this is how a python list is printed")

[111   2   3   4] this is a numpy array
[1, 2, 3, 4] this is a python list


In [6]:
a = np.array((1,2,3,4), dtype=np.int16)
b = [1,2,3,4]

x = a[1:3]
y = b[1:3]

x[0] = 22
y[0] = 22

print(a, b)

[ 1 22  3  4] [1, 2, 3, 4]


In [28]:
mat = np.array(([1,2,3],[4,5,6]))
print(mat.shape) # row, col
print(mat.ndim)
print(mat.size)

(2, 3)
2
6


In [7]:
a = np.zeros((2,3,4), dtype = np.int32) # this is the shape of the numpy array
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [33]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
c = np.empty((2, 2), 5)
c

array([0.00000000e+000, 1.24284904e-311, 1.24284904e-311, 1.24284904e-311,
       0.00000000e+000])

: 

In [ ]:
ab = np.arange(1, 11, 2) # a lot like splicing, start (inclusive), end(exclusive), step (i += step)
ab

array([1, 3, 5, 7, 9])

In [42]:
bc = np.linspace(20, 100, 9)
bc

array([ 20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# ca = np.random.random((2, 3))
ca = np.random.uniform(0, 10, (2,3)) # 0 theke 10 er moddhe (2, 3) shape er
ca

array([[6.99199176, 3.57067126, 1.83081623],
       [8.85061016, 1.31932175, 7.67901089]])

In [53]:
a = np.random.random(10)
print(a)

# a = np.sort(a)
a.sort()
print(a)

[0.35838807 0.22805879 0.32658842 0.60590958 0.99941161 0.66800513
 0.68412836 0.64466625 0.14639005 0.62601625]
[0.14639005 0.22805879 0.32658842 0.35838807 0.60590958 0.62601625
 0.64466625 0.66800513 0.68412836 0.99941161]


In [69]:
a = np.random.random((2,3))
b = np.random.random((2,4))
# print(a, b)

# c = np.vstack((a,b))
# print(c)

d = np.hstack((a,b))
print(d)

[[0.84440295 0.0433714  0.78406417 0.92303878 0.63803143 0.43649483
  0.47230879]
 [0.7451573  0.60281745 0.30740881 0.88195856 0.74328419 0.0141301
  0.53689348]]


In [77]:
a = np.random.random(6)
b = np.split(a,3)
b

[array([0.80201694, 0.29899384]),
 array([0.81895841, 0.91651745]),
 array([0.84008691, 0.33273126])]

In [88]:
a = np.random.random((4,4))
b = np.random.random((4,1))
print(a)
print(b)
a + b

[[0.95862379 0.69310919 0.03075945 0.02840498]
 [0.6692577  0.37940288 0.67611201 0.77827522]
 [0.06239942 0.90857434 0.40122105 0.04988694]
 [0.37106744 0.66977201 0.75942146 0.79629211]]
[[0.44886402]
 [0.79172952]
 [0.15983397]
 [0.84075841]]


array([[1.40748781, 1.14197321, 0.47962346, 0.477269  ],
       [1.46098721, 1.1711324 , 1.46784152, 1.57000473],
       [0.22223339, 1.06840831, 0.56105503, 0.20972091],
       [1.21182585, 1.51053042, 1.60017987, 1.63705052]])

In [ ]:
a = np.random.random((2,3)) * 10
print(a)
a.max(axis=1)

# axis 0 downward
# axis 1 towards right

[[0.42387496 0.86909356 0.35352369]
 [0.11978202 0.63629716 0.15007391]]


array([0.86909356, 0.63629716])

In [ ]:
np.exp